feat: problem 도메인 임시 구현 (미완, 임시 커밋)
YAPP-Github/24th-Web-Team-1-BE pull request #49
Opened 2024-06-17 16:04 UTC by hun-ca

🎫 연관 이슈
---
resolved:

💁‍♂️ PR 내용
----

🙏 작업
----

🙈 PR 참고 사항
----

📸 스크린샷
----

🤖 테스트 체크리스트
----
- [ ] 체크 미완료
- [x] 체크 완료

2024-06-20 14:10 UTC, belljun3395 requested changes

2024-06-20 14:10 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +        val record = problemDao.selectProblemAnswer(SelectProblemAnswerQuery(problemId))
저는 

```kotlin
val record = SelectProblemAnswerQuery(problemId).let {
    problemDao.selectProblemAnswer(it);
}
```
위와 같이 코드를 작성하였는데 `let`을 사용하는 것은 어떨까요?

아직 코틀린을 잘 모르지만 `let`이 nullsafe도 된다고 하니..?

2024-06-20 14:10 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +        val isSolved = submitAns.equals(record.answer)
```kotlin
record.answer.equals(submitAns)
```
위와 같이 순서를 변경하거나 

submitAns는 모델을 만들어 처리하는게 어떨까요?

2024-06-20 14:10 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +
위의 리뷰와 동일

2024-06-20 14:10 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/usecase/problem/ReadProblemUseCase.kt
> +        val contents: List<ReadProblemContentsUseCaseOut> = objectMapper.readValue(record.contents)
요거는 제가 contents 관련 mapper와 객체를 만들었는데 같이 사용하는 것은 어떨까요?

2024-06-20 14:10 UTC, belljun3395 commented on api/src/main/resources/application.yaml
> +spring:
application.yml 이 있어서 삭제해야할 것 같습니다

2024-06-20 14:10 UTC, belljun3395 commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +            .fetchOne()
fetchInto()라는 메서드가 있는데 해당 메서드를 사용하면 값과 객체를 매핑해줍니다

2024-06-20 14:10 UTC, belljun3395 commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +        result ?: throw RuntimeException("Problem with ID ${query.problemId} not found") // TODO: 에러 표준화
저는 잘못된 인자로 조회했어! 라는 의미로 IllegalArgumentException를 주로 사용해 오기는 했는데 어떤 예외를 상속에 사용하는게 좋을까요?

2024-06-20 14:10 UTC, belljun3395 commented on api-repo/src/main/resources/db/migration/entity/V1.00.0.0__draft_table_design.sql
> +-- 작가 및 유저
해당 파일은 커밋에서 제외해야 할 것 같습니다

2024-06-20 14:10 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/controller/problem/ProblemController.kt
>      fun readProblem(
목 응답을 제외하여 컨트롤러 테스트에 UseCase를 목 빈으로 선언하는 작업이 필요합니다

2024-06-20 14:10 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/controller/problem/ProblemController.kt
>      @PostMapping("/{problemId}")
위와 동일한 목 작업이 필요합니다

2024-06-20 14:20 UTC, belljun3395 commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +class ProblemDao(
혹시 Dao의 메서드에 도메인 Id만으로 조회하는게 아니면 ByXXX( XXXByXXXQuery) 이케 네이밍 하는게 어떤가요?

2024-06-22 07:51 UTC, hun-ca commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +        val record = problemDao.selectProblemAnswer(SelectProblemAnswerQuery(problemId))
`SelectProblemAnswerQuery(problemId)` << 이게 널러블이 될 가능성이 있을지 확인해볼게요

2024-06-22 07:52 UTC, hun-ca commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +        val isSolved = submitAns.equals(record.answer)
아,, 이런거 생각하면 JPA가 좋긴 하구나...

2024-06-22 07:55 UTC, hun-ca commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +        val record = problemDao.selectProblemAnswer(SelectProblemAnswerQuery(problemId))
추가로 uc 까지 들어온 이상 problemID 같은 DTO는 널러블 가정 X로 가는게 좋을거 같습니다 (지금처럼)

2024-06-22 07:56 UTC, hun-ca commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +
그러면 서비스가 필요할 일이 있을까요 서비스 뺴고 모델로 가도 될거 같은데

2024-06-22 07:58 UTC, hun-ca commented on api/src/main/kotlin/com/few/api/web/usecase/problem/ReadProblemUseCase.kt
> +        val contents: List<ReadProblemContentsUseCaseOut> = objectMapper.readValue(record.contents)
json string <-> kotlin class 매퍼인가요?

2024-06-22 08:07 UTC, hun-ca commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +            .fetchOne()
아래처럼 jooq 클래스가 아닌 사용자 정의 클래스 (SelectProblemRecord) 로 매핑은 따로 주크에서 지원 안해주는거 같네요
`        val problem = dslContext.select(Problem.PROBLEM.ID, Problem.PROBLEM.TITLE, Problem.PROBLEM.CONTENTS)
            .from(Problem.PROBLEM)
            .where(Problem.PROBLEM.ID.eq(query.problemId))
            .fetchInto(SelectProblemRecord.class)`

2024-06-22 08:08 UTC, hun-ca commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +            .fetchOne()
아래처럼 PROBLEM으로 매핑은 가능

```
        val problem = dslContext.select(Problem.PROBLEM.ID, Problem.PROBLEM.TITLE, Problem.PROBLEM.CONTENTS)
            .from(Problem.PROBLEM)
            .where(Problem.PROBLEM.ID.eq(query.problemId))
            .fetchInto(Problem.PROBLEM)
```

2024-06-22 08:08 UTC, hun-ca commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +            .fetchOne()
매퍼 같은거 지정해주면 바로 되는지 찾아봐야곘네

2024-06-22 08:09 UTC, hun-ca commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +        result ?: throw RuntimeException("Problem with ID ${query.problemId} not found") // TODO: 에러 표준화
저도 주석으로 에러 표준화라고 적어두긴 했는데 자바꺼 말고 저희단에서 예외 클래스 만들어서 쓰는건 어떨까요

2024-06-22 08:12 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/usecase/problem/ReadProblemUseCase.kt
> +        val contents: List<ReadProblemContentsUseCaseOut> = objectMapper.readValue(record.contents)
5ac73039c9c2acf648f96898fa83c6f93770f6cc 요런거요

2024-06-22 08:13 UTC, belljun3395 commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +            .fetchOne()
f0a9f37eba7be6f361d44c761d0bbae90308e88a 이렇게 가능합니다

2024-06-22 08:16 UTC, belljun3395 commented on api/src/main/kotlin/com/few/api/web/usecase/problem/CheckProblemUseCase.kt
> +
https://github.com/YAPP-Github/24th-Web-Team-1-BE/pull/49/files/a673c6359c3053ed1afcd13569bf8408b80f9176#r1647633696

아 요 리뷰 말한거였어요

2024-06-22 08:32 UTC, hun-ca commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +            .fetchOne()
오 좋네...

2024-06-22 08:48 UTC, hun-ca commented on api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
> +class ProblemDao(
좋습니다~

2024-06-22 08:49 UTC, hun-ca commented on api/src/main/kotlin/com/few/api/web/usecase/problem/out/ReadProblemUseCaseOut.kt
> +data class ReadProblemContentsUseCaseOut(
네넵 좋아요

2024-06-22 08:57 UTC, hun-ca commented on api/src/main/kotlin/com/few/api/web/usecase/problem/ReadProblemUseCase.kt
> +        val contents: List<ReadProblemContentsUseCaseOut> = objectMapper.readValue(record.contents)
이거 근데 uc 단에서도 한번 바꿔주고 컨트롤러단에서도 response로 또 한번 바꿔줘야겠네요...

2024-06-22 10:44 UTC, hun-ca commented
@belljun3395 종준님 컨트롤러 테스트 시 포트를 띄워야 하기 때문에 WAS가 올라가야 하는데 이때 데이터소스 같은 불필요한 클래스는 컨테이너에 로딩되지 않도록 설정필요합니다. 코파일럿의 힘을 빌려 함 해주세요

2024-06-22 12:12 UTC, belljun3395 reviewed
Problem 도메인에서 ProblemId로 조회하는 경우에는 ByProblemId를 안붙이고
추후 Title이나 다른 것으로 조회하는 경우에만 ByTitle 이런 식으로 붙이는게 어떨까요?

2024-06-22 12:15 UTC, belljun3395 commented on api/src/test/kotlin/com/few/api/web/controller/problem/ProblemControllerTest.kt
> +        Mockito.`when`(readProblemUseCase.execute(ArgumentMatchers.any()))
저는 요렇게 any 처리가 NPE 뜨면서 안되던데 혹시 테스트 성공하나요?

2024-06-23 00:34 UTC, belljun3395 approved these changes
테스트 코드만 동작하도록 수정하고 머지하면 될 것 같아요!
수고하셨습니다~!

2024-06-23 00:34 UTC, belljun3395 commented on api/src/test/kotlin/com/few/api/web/controller/problem/ProblemControllerTest.kt
> +        Mockito.`when`(readProblemUseCase.execute(ArgumentMatchers.any()))
```kotlin
val problemId = 1L
Mockito.`when`(readProblemUseCase.execute(ReadProblemUseCaseIn(problemId)))
    .thenReturn(useCaseOut)
```
요렇게 테스트 코드 수정해주시면 될 것 같아요

2024-06-23 00:34 UTC, belljun3395 commented on api/src/test/kotlin/com/few/api/web/controller/problem/ProblemControllerTest.kt
> +            .thenReturn(useCaseOut)
```kotlin
// set usecase mock
val problemId = 1L
val sub = "sub"
val useCaseOut = CheckProblemUseCaseOut(
    explanation = "ETF는 일반적으로 낮은 운용 비용을 특징으로 합니다.이는 ETF가 보통 지수 추종(passive management) 방식으로 운용되기 때문입니다. 지수를 추종하는 전략은 액티브 매니지먼트(active management)에 비해 관리가 덜 복잡하고, 따라서 비용이 낮습니다.",
    answer = "2",
    isSolved = true
)
Mockito.`when`(checkProblemUseCase.execute(CheckProblemUseCaseIn(problemId, sub = sub)))
    .thenReturn(useCaseOut)
````
요기도 이렇게 수정해야할 것 같아요!

2024-06-23 03:08 UTC, hun-ca commented
> [9c23cae](https://github.com/YAPP-Github/24th-Web-Team-1-BE/commit/9c23cae89c40956cc7b8d9764c2f526f14d72bfa) Problem 도메인에서 ProblemId로 조회하는 경우에는 ByProblemId를 안붙이고 추후 Title이나 다른 것으로 조회하는 경우에만 ByTitle 이런 식으로 붙이는게 어떨까요?

@belljun3395  네넵 좋습니다 ID로 조회하는 것만 네이밍에서 제외할게요

2024-06-23 03:17 UTC, merged